/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Discovery_ReceiveFSMContext.sm
 */

package src.urn_jaus_jss_core_Discovery_1_0;

import framework.internalEvents.*;
import src.urn_jaus_jss_core_Discovery_1_0.InternalEvents.*;
import src.urn_jaus_jss_core_Discovery_1_0.Messages.*;
import java.io.PrintStream;

public class Discovery_ReceiveFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public Discovery_ReceiveFSMContext(Discovery_ReceiveFSM owner)
    {
        super (Discovery_ReceiveFSM_SM.Receiving_Ready);

        _owner = owner;
    }

    public Discovery_ReceiveFSMContext(Discovery_ReceiveFSM owner, Discovery_ReceiveFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void QueryConfigurationTransition()
    {
        _transition = "QueryConfigurationTransition";
        getState().QueryConfigurationTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void QueryIdentificationTransition()
    {
        _transition = "QueryIdentificationTransition";
        getState().QueryIdentificationTransition(this);
        _transition = "";
        return;
    }

    public void QueryServicesTransition()
    {
        _transition = "QueryServicesTransition";
        getState().QueryServicesTransition(this);
        _transition = "";
        return;
    }

    public void QuerySubsystemListTransition()
    {
        _transition = "QuerySubsystemListTransition";
        getState().QuerySubsystemListTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryConfiguration msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryIdentification msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryServices msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QuerySubsystemList msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(RegisterServices msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(ReportIdentification msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void RegisterServicesTransition()
    {
        _transition = "RegisterServicesTransition";
        getState().RegisterServicesTransition(this);
        _transition = "";
        return;
    }

    public void ReportIdentificationTransition()
    {
        _transition = "ReportIdentificationTransition";
        getState().ReportIdentificationTransition(this);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public Discovery_ReceiveFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((Discovery_ReceiveFSMState) _state);
    }

    protected Discovery_ReceiveFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(Discovery_ReceiveFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private Discovery_ReceiveFSM _owner;

    public static abstract class Discovery_ReceiveFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Discovery_ReceiveFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(Discovery_ReceiveFSMContext context) {}
        protected void Exit(Discovery_ReceiveFSMContext context) {}

        protected void BroadcastGlobalTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryConfigurationTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryIdentificationTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryServicesTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QuerySubsystemListTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryConfiguration msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryIdentification msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryServices msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QuerySubsystemList msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, RegisterServices msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, ReportIdentification msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void RegisterServicesTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReportIdentificationTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void SendTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(Discovery_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void Default(Discovery_ReceiveFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class Discovery_ReceiveFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final Discovery_ReceiveFSM_SM_Receiving_Ready Receiving_Ready =
            new Discovery_ReceiveFSM_SM_Receiving_Ready("Discovery_ReceiveFSM_SM.Receiving_Ready", 0);
        public static final Discovery_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new Discovery_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE("Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE", 1);
        private static final Discovery_ReceiveFSM_SM_Default Default =
            new Discovery_ReceiveFSM_SM_Default("Discovery_ReceiveFSM_SM.Default", -1);

    }

    protected static class Discovery_ReceiveFSM_SM_Default
        extends Discovery_ReceiveFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Discovery_ReceiveFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    private static final class Discovery_ReceiveFSM_SM_Receiving_Ready
        extends Discovery_ReceiveFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Discovery_ReceiveFSM_SM_Receiving_Ready(String name, int id)
        {
            super (name, id);
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryConfiguration msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryConfiguration msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.SendAction("ReportConfiguration", transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryConfiguration msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryIdentification msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryIdentification msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.ReplyToQueryIdentification(msg, transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryIdentification msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QueryServices msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryServices msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.SendAction("ReportServices", transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QueryServices msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, QuerySubsystemList msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QuerySubsystemList msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.SendAction("ReportSubsystemList", transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(QuerySubsystemList msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, RegisterServices msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(RegisterServices msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.PublishServicesAction(msg, transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(RegisterServices msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context, ReportIdentification msg, Receive.Body.ReceiveRec transportData)
        {
            Discovery_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Receiving_Ready");
            }
            Discovery_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(ReportIdentification msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.handleReportIdentificationAction(msg, transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Receiving_Ready.ReceiveTransition(ReportIdentification msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class Discovery_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE
        extends Discovery_ReceiveFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Discovery_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
        {
            super (name, id);
        }

        protected void BroadcastGlobalTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            return;
        }

        protected void BroadcastLocalTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            return;
        }

        protected void CancelEventTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            return;
        }

        protected void CreateEventTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            return;
        }

        protected void EventErrorTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            return;
        }

        protected void EventOccurredTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            return;
        }

        protected void QueryConfigurationTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryConfigurationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryConfigurationTransition()");
            }

            return;
        }

        protected void QueryEventsTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            return;
        }

        protected void QueryIdentificationTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryIdentificationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryIdentificationTransition()");
            }

            return;
        }

        protected void QueryServicesTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryServicesTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryServicesTransition()");
            }

            return;
        }

        protected void QuerySubsystemListTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QuerySubsystemListTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QuerySubsystemListTransition()");
            }

            return;
        }

        protected void ReceiveTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            return;
        }

        protected void RegisterServicesTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.RegisterServicesTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.RegisterServicesTransition()");
            }

            return;
        }

        protected void ReportIdentificationTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReportIdentificationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReportIdentificationTransition()");
            }

            return;
        }

        protected void SendTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            return;
        }

        protected void UpdateEventTransition(Discovery_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_ReceiveFSM_SM.Discovery_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
