/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : Discovery_SendFSMContext.sm
 */

package src.urn_jaus_jss_core_Discovery_1_0;

import framework.internalEvents.*;
import src.urn_jaus_jss_core_Discovery_1_0.InternalEvents.*;
import src.urn_jaus_jss_core_Discovery_1_0.Messages.*;
import java.io.PrintStream;

public class Discovery_SendFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public Discovery_SendFSMContext(Discovery_SendFSM owner)
    {
        super (Discovery_SendFSM_SM.Sending);

        _owner = owner;
    }

    public Discovery_SendFSMContext(Discovery_SendFSM owner, Discovery_SendFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void QueryConfigurationTransition()
    {
        _transition = "QueryConfigurationTransition";
        getState().QueryConfigurationTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void QueryIdentificationTransition()
    {
        _transition = "QueryIdentificationTransition";
        getState().QueryIdentificationTransition(this);
        _transition = "";
        return;
    }

    public void QueryServicesTransition()
    {
        _transition = "QueryServicesTransition";
        getState().QueryServicesTransition(this);
        _transition = "";
        return;
    }

    public void QuerySubsystemListTransition()
    {
        _transition = "QuerySubsystemListTransition";
        getState().QuerySubsystemListTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void RegisterServicesTransition()
    {
        _transition = "RegisterServicesTransition";
        getState().RegisterServicesTransition(this);
        _transition = "";
        return;
    }

    public void ReportIdentificationTransition()
    {
        _transition = "ReportIdentificationTransition";
        getState().ReportIdentificationTransition(this);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public Discovery_SendFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((Discovery_SendFSMState) _state);
    }

    protected Discovery_SendFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(Discovery_SendFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private Discovery_SendFSM _owner;

    public static abstract class Discovery_SendFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Discovery_SendFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(Discovery_SendFSMContext context) {}
        protected void Exit(Discovery_SendFSMContext context) {}

        protected void BroadcastGlobalTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryConfigurationTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryIdentificationTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryServicesTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void QuerySubsystemListTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void RegisterServicesTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReportIdentificationTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void SendTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(Discovery_SendFSMContext context)
        {
            Default(context);
        }

        protected void Default(Discovery_SendFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class Discovery_SendFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final Discovery_SendFSM_SM_Sending Sending =
            new Discovery_SendFSM_SM_Sending("Discovery_SendFSM_SM.Sending", 0);
        public static final Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE("Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE", 1);
        private static final Discovery_SendFSM_SM_Default Default =
            new Discovery_SendFSM_SM_Default("Discovery_SendFSM_SM.Default", -1);

    }

    protected static class Discovery_SendFSM_SM_Default
        extends Discovery_SendFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Discovery_SendFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    private static final class Discovery_SendFSM_SM_Sending
        extends Discovery_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Discovery_SendFSM_SM_Sending(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE
        extends Discovery_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Discovery_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
        {
            super (name, id);
        }

        protected void BroadcastGlobalTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            return;
        }

        protected void BroadcastLocalTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            return;
        }

        protected void CancelEventTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            return;
        }

        protected void CreateEventTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            return;
        }

        protected void EventErrorTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            return;
        }

        protected void EventOccurredTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            return;
        }

        protected void QueryConfigurationTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryConfigurationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryConfigurationTransition()");
            }

            return;
        }

        protected void QueryEventsTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            return;
        }

        protected void QueryIdentificationTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryIdentificationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryIdentificationTransition()");
            }

            return;
        }

        protected void QueryServicesTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryServicesTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryServicesTransition()");
            }

            return;
        }

        protected void QuerySubsystemListTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QuerySubsystemListTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QuerySubsystemListTransition()");
            }

            return;
        }

        protected void ReceiveTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            return;
        }

        protected void RegisterServicesTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RegisterServicesTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RegisterServicesTransition()");
            }

            return;
        }

        protected void ReportIdentificationTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReportIdentificationTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReportIdentificationTransition()");
            }

            return;
        }

        protected void SendTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            return;
        }

        protected void UpdateEventTransition(Discovery_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : Discovery_SendFSM_SM.Discovery_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
