/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : LocalWaypointListDriver_SendFSMContext.sm
 */

package src.urn_jaus_jss_mobility_LocalWaypointListDriver_1_0;

import framework.internalEvents.*;
import src.urn_jaus_jss_mobility_LocalWaypointListDriver_1_0.InternalEvents.*;
import src.urn_jaus_jss_mobility_LocalWaypointListDriver_1_0.Messages.*;
import java.io.PrintStream;

public class LocalWaypointListDriver_SendFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public LocalWaypointListDriver_SendFSMContext(LocalWaypointListDriver_SendFSM owner)
    {
        super (LocalWaypointListDriver_SendFSM_SM.Sending);

        _owner = owner;
    }

    public LocalWaypointListDriver_SendFSMContext(LocalWaypointListDriver_SendFSM owner, LocalWaypointListDriver_SendFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void ClearEmergencyTransition()
    {
        _transition = "ClearEmergencyTransition";
        getState().ClearEmergencyTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void DeleteElementTransition()
    {
        _transition = "DeleteElementTransition";
        getState().DeleteElementTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void ExecuteListTransition()
    {
        _transition = "ExecuteListTransition";
        getState().ExecuteListTransition(this);
        _transition = "";
        return;
    }

    public void FailureTransition()
    {
        _transition = "FailureTransition";
        getState().FailureTransition(this);
        _transition = "";
        return;
    }

    public void InitializedTransition()
    {
        _transition = "InitializedTransition";
        getState().InitializedTransition(this);
        _transition = "";
        return;
    }

    public void QueryActiveElementTransition()
    {
        _transition = "QueryActiveElementTransition";
        getState().QueryActiveElementTransition(this);
        _transition = "";
        return;
    }

    public void QueryAuthorityTransition()
    {
        _transition = "QueryAuthorityTransition";
        getState().QueryAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void QueryControlTransition()
    {
        _transition = "QueryControlTransition";
        getState().QueryControlTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementCountTransition()
    {
        _transition = "QueryElementCountTransition";
        getState().QueryElementCountTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementListTransition()
    {
        _transition = "QueryElementListTransition";
        getState().QueryElementListTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementTransition()
    {
        _transition = "QueryElementTransition";
        getState().QueryElementTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void QueryLocalWaypointTransition()
    {
        _transition = "QueryLocalWaypointTransition";
        getState().QueryLocalWaypointTransition(this);
        _transition = "";
        return;
    }

    public void QueryStatusTransition()
    {
        _transition = "QueryStatusTransition";
        getState().QueryStatusTransition(this);
        _transition = "";
        return;
    }

    public void QueryTimeoutTransition()
    {
        _transition = "QueryTimeoutTransition";
        getState().QueryTimeoutTransition(this);
        _transition = "";
        return;
    }

    public void QueryTravelSpeedTransition()
    {
        _transition = "QueryTravelSpeedTransition";
        getState().QueryTravelSpeedTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void ReleaseControlTransition()
    {
        _transition = "ReleaseControlTransition";
        getState().ReleaseControlTransition(this);
        _transition = "";
        return;
    }

    public void RequestControlTransition()
    {
        _transition = "RequestControlTransition";
        getState().RequestControlTransition(this);
        _transition = "";
        return;
    }

    public void ResetTransition()
    {
        _transition = "ResetTransition";
        getState().ResetTransition(this);
        _transition = "";
        return;
    }

    public void ResumeTransition()
    {
        _transition = "ResumeTransition";
        getState().ResumeTransition(this);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void SetAuthorityTransition()
    {
        _transition = "SetAuthorityTransition";
        getState().SetAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void SetElementTransition()
    {
        _transition = "SetElementTransition";
        getState().SetElementTransition(this);
        _transition = "";
        return;
    }

    public void SetEmergencyTransition()
    {
        _transition = "SetEmergencyTransition";
        getState().SetEmergencyTransition(this);
        _transition = "";
        return;
    }

    public void ShutdownTransition()
    {
        _transition = "ShutdownTransition";
        getState().ShutdownTransition(this);
        _transition = "";
        return;
    }

    public void StandbyTransition()
    {
        _transition = "StandbyTransition";
        getState().StandbyTransition(this);
        _transition = "";
        return;
    }

    public void TimeoutTransition()
    {
        _transition = "TimeoutTransition";
        getState().TimeoutTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public LocalWaypointListDriver_SendFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((LocalWaypointListDriver_SendFSMState) _state);
    }

    protected LocalWaypointListDriver_SendFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(LocalWaypointListDriver_SendFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private LocalWaypointListDriver_SendFSM _owner;

    public static abstract class LocalWaypointListDriver_SendFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected LocalWaypointListDriver_SendFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(LocalWaypointListDriver_SendFSMContext context) {}
        protected void Exit(LocalWaypointListDriver_SendFSMContext context) {}

        protected void BroadcastGlobalTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ClearEmergencyTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void DeleteElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ExecuteListTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void FailureTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void InitializedTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryActiveElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryAuthorityTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementCountTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementListTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryLocalWaypointTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryStatusTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryTimeoutTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryTravelSpeedTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReleaseControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void RequestControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ResetTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ResumeTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void SendTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetAuthorityTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetEmergencyTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void ShutdownTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void StandbyTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void TimeoutTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {
            Default(context);
        }

        protected void Default(LocalWaypointListDriver_SendFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class LocalWaypointListDriver_SendFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final LocalWaypointListDriver_SendFSM_SM_Sending Sending =
            new LocalWaypointListDriver_SendFSM_SM_Sending("LocalWaypointListDriver_SendFSM_SM.Sending", 0);
        public static final LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE("LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE", 1);
        private static final LocalWaypointListDriver_SendFSM_SM_Default Default =
            new LocalWaypointListDriver_SendFSM_SM_Default("LocalWaypointListDriver_SendFSM_SM.Default", -1);

    }

    protected static class LocalWaypointListDriver_SendFSM_SM_Default
        extends LocalWaypointListDriver_SendFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected LocalWaypointListDriver_SendFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    private static final class LocalWaypointListDriver_SendFSM_SM_Sending
        extends LocalWaypointListDriver_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private LocalWaypointListDriver_SendFSM_SM_Sending(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE
        extends LocalWaypointListDriver_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private LocalWaypointListDriver_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
        {
            super (name, id);
        }

        protected void BroadcastGlobalTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            return;
        }

        protected void BroadcastLocalTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            return;
        }

        protected void CancelEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            return;
        }

        protected void ClearEmergencyTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ClearEmergencyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ClearEmergencyTransition()");
            }

            return;
        }

        protected void CreateEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            return;
        }

        protected void DeleteElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.DeleteElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.DeleteElementTransition()");
            }

            return;
        }

        protected void EventErrorTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            return;
        }

        protected void EventOccurredTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            return;
        }

        protected void ExecuteListTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ExecuteListTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ExecuteListTransition()");
            }

            return;
        }

        protected void FailureTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.FailureTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.FailureTransition()");
            }

            return;
        }

        protected void InitializedTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.InitializedTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.InitializedTransition()");
            }

            return;
        }

        protected void QueryActiveElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryActiveElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryActiveElementTransition()");
            }

            return;
        }

        protected void QueryAuthorityTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            return;
        }

        protected void QueryControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            return;
        }

        protected void QueryElementCountTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementCountTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementCountTransition()");
            }

            return;
        }

        protected void QueryElementListTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementListTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementListTransition()");
            }

            return;
        }

        protected void QueryElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementTransition()");
            }

            return;
        }

        protected void QueryEventsTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            return;
        }

        protected void QueryLocalWaypointTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryLocalWaypointTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryLocalWaypointTransition()");
            }

            return;
        }

        protected void QueryStatusTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryStatusTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryStatusTransition()");
            }

            return;
        }

        protected void QueryTimeoutTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            return;
        }

        protected void QueryTravelSpeedTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTravelSpeedTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTravelSpeedTransition()");
            }

            return;
        }

        protected void ReceiveTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            return;
        }

        protected void ReleaseControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            return;
        }

        protected void RequestControlTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            return;
        }

        protected void ResetTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResetTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResetTransition()");
            }

            return;
        }

        protected void ResumeTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResumeTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResumeTransition()");
            }

            return;
        }

        protected void SendTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            return;
        }

        protected void SetAuthorityTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            return;
        }

        protected void SetElementTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetElementTransition()");
            }

            return;
        }

        protected void SetEmergencyTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetEmergencyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetEmergencyTransition()");
            }

            return;
        }

        protected void ShutdownTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ShutdownTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ShutdownTransition()");
            }

            return;
        }

        protected void StandbyTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.StandbyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.StandbyTransition()");
            }

            return;
        }

        protected void TimeoutTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            return;
        }

        protected void UpdateEventTransition(LocalWaypointListDriver_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalWaypointListDriver_SendFSM_SM.LocalWaypointListDriver_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
