/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : ListManager_SendFSMContext.sm
 */

package src.urn_jaus_jss_mobility_ListManager_1_0;

import framework.internalEvents.*;
import src.urn_jaus_jss_mobility_ListManager_1_0.InternalEvents.*;
import src.urn_jaus_jss_mobility_ListManager_1_0.Messages.*;
import java.io.PrintStream;

public class ListManager_SendFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public ListManager_SendFSMContext(ListManager_SendFSM owner)
    {
        super (ListManager_SendFSM_SM.Sending);

        _owner = owner;
    }

    public ListManager_SendFSMContext(ListManager_SendFSM owner, ListManager_SendFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void ClearEmergencyTransition()
    {
        _transition = "ClearEmergencyTransition";
        getState().ClearEmergencyTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void DeleteElementTransition()
    {
        _transition = "DeleteElementTransition";
        getState().DeleteElementTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void FailureTransition()
    {
        _transition = "FailureTransition";
        getState().FailureTransition(this);
        _transition = "";
        return;
    }

    public void InitializedTransition()
    {
        _transition = "InitializedTransition";
        getState().InitializedTransition(this);
        _transition = "";
        return;
    }

    public void QueryAuthorityTransition()
    {
        _transition = "QueryAuthorityTransition";
        getState().QueryAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void QueryControlTransition()
    {
        _transition = "QueryControlTransition";
        getState().QueryControlTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementCountTransition()
    {
        _transition = "QueryElementCountTransition";
        getState().QueryElementCountTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementListTransition()
    {
        _transition = "QueryElementListTransition";
        getState().QueryElementListTransition(this);
        _transition = "";
        return;
    }

    public void QueryElementTransition()
    {
        _transition = "QueryElementTransition";
        getState().QueryElementTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void QueryStatusTransition()
    {
        _transition = "QueryStatusTransition";
        getState().QueryStatusTransition(this);
        _transition = "";
        return;
    }

    public void QueryTimeoutTransition()
    {
        _transition = "QueryTimeoutTransition";
        getState().QueryTimeoutTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void ReleaseControlTransition()
    {
        _transition = "ReleaseControlTransition";
        getState().ReleaseControlTransition(this);
        _transition = "";
        return;
    }

    public void RequestControlTransition()
    {
        _transition = "RequestControlTransition";
        getState().RequestControlTransition(this);
        _transition = "";
        return;
    }

    public void ResetTransition()
    {
        _transition = "ResetTransition";
        getState().ResetTransition(this);
        _transition = "";
        return;
    }

    public void ResumeTransition()
    {
        _transition = "ResumeTransition";
        getState().ResumeTransition(this);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void SetAuthorityTransition()
    {
        _transition = "SetAuthorityTransition";
        getState().SetAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void SetElementTransition()
    {
        _transition = "SetElementTransition";
        getState().SetElementTransition(this);
        _transition = "";
        return;
    }

    public void SetEmergencyTransition()
    {
        _transition = "SetEmergencyTransition";
        getState().SetEmergencyTransition(this);
        _transition = "";
        return;
    }

    public void ShutdownTransition()
    {
        _transition = "ShutdownTransition";
        getState().ShutdownTransition(this);
        _transition = "";
        return;
    }

    public void StandbyTransition()
    {
        _transition = "StandbyTransition";
        getState().StandbyTransition(this);
        _transition = "";
        return;
    }

    public void TimeoutTransition()
    {
        _transition = "TimeoutTransition";
        getState().TimeoutTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public ListManager_SendFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((ListManager_SendFSMState) _state);
    }

    protected ListManager_SendFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(ListManager_SendFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private ListManager_SendFSM _owner;

    public static abstract class ListManager_SendFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected ListManager_SendFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(ListManager_SendFSMContext context) {}
        protected void Exit(ListManager_SendFSMContext context) {}

        protected void BroadcastGlobalTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ClearEmergencyTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void DeleteElementTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void FailureTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void InitializedTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryAuthorityTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryControlTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementCountTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementListTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryElementTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryStatusTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void QueryTimeoutTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ReleaseControlTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void RequestControlTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ResetTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ResumeTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void SendTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetAuthorityTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetElementTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void SetEmergencyTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void ShutdownTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void StandbyTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void TimeoutTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(ListManager_SendFSMContext context)
        {
            Default(context);
        }

        protected void Default(ListManager_SendFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class ListManager_SendFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final ListManager_SendFSM_SM_Sending Sending =
            new ListManager_SendFSM_SM_Sending("ListManager_SendFSM_SM.Sending", 0);
        public static final ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE("ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE", 1);
        private static final ListManager_SendFSM_SM_Default Default =
            new ListManager_SendFSM_SM_Default("ListManager_SendFSM_SM.Default", -1);

    }

    protected static class ListManager_SendFSM_SM_Default
        extends ListManager_SendFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected ListManager_SendFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    private static final class ListManager_SendFSM_SM_Sending
        extends ListManager_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private ListManager_SendFSM_SM_Sending(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE
        extends ListManager_SendFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private ListManager_SendFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
        {
            super (name, id);
        }

        protected void BroadcastGlobalTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            return;
        }

        protected void BroadcastLocalTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            return;
        }

        protected void CancelEventTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            return;
        }

        protected void ClearEmergencyTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ClearEmergencyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ClearEmergencyTransition()");
            }

            return;
        }

        protected void CreateEventTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            return;
        }

        protected void DeleteElementTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.DeleteElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.DeleteElementTransition()");
            }

            return;
        }

        protected void EventErrorTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            return;
        }

        protected void EventOccurredTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            return;
        }

        protected void FailureTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.FailureTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.FailureTransition()");
            }

            return;
        }

        protected void InitializedTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.InitializedTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.InitializedTransition()");
            }

            return;
        }

        protected void QueryAuthorityTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            return;
        }

        protected void QueryControlTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            return;
        }

        protected void QueryElementCountTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementCountTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementCountTransition()");
            }

            return;
        }

        protected void QueryElementListTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementListTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementListTransition()");
            }

            return;
        }

        protected void QueryElementTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryElementTransition()");
            }

            return;
        }

        protected void QueryEventsTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            return;
        }

        protected void QueryStatusTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryStatusTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryStatusTransition()");
            }

            return;
        }

        protected void QueryTimeoutTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            return;
        }

        protected void ReceiveTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            return;
        }

        protected void ReleaseControlTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            return;
        }

        protected void RequestControlTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            return;
        }

        protected void ResetTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResetTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResetTransition()");
            }

            return;
        }

        protected void ResumeTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResumeTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ResumeTransition()");
            }

            return;
        }

        protected void SendTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            return;
        }

        protected void SetAuthorityTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            return;
        }

        protected void SetElementTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetElementTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetElementTransition()");
            }

            return;
        }

        protected void SetEmergencyTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetEmergencyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.SetEmergencyTransition()");
            }

            return;
        }

        protected void ShutdownTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ShutdownTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.ShutdownTransition()");
            }

            return;
        }

        protected void StandbyTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.StandbyTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.StandbyTransition()");
            }

            return;
        }

        protected void TimeoutTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            return;
        }

        protected void UpdateEventTransition(ListManager_SendFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : ListManager_SendFSM_SM.ListManager_SendFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
