/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : LocalPoseSensor_ReceiveFSMContext.sm
 */

package src.urn_jaus_jss_mobility_LocalPoseSensor_1_0;

import framework.internalEvents.*;
import src.urn_jaus_jss_mobility_LocalPoseSensor_1_0.InternalEvents.*;
import src.urn_jaus_jss_mobility_LocalPoseSensor_1_0.Messages.*;
import java.io.PrintStream;

public class LocalPoseSensor_ReceiveFSMContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public LocalPoseSensor_ReceiveFSMContext(LocalPoseSensor_ReceiveFSM owner)
    {
        super (LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled);

        _owner = owner;
    }

    public LocalPoseSensor_ReceiveFSMContext(LocalPoseSensor_ReceiveFSM owner, LocalPoseSensor_ReceiveFSMState initState)
    {
        super (initState);

        _owner = owner;
    }

    public void enterStartState()
    {
        getState().Entry(this);
        return;
    }

    public void BroadcastGlobalTransition()
    {
        _transition = "BroadcastGlobalTransition";
        getState().BroadcastGlobalTransition(this);
        _transition = "";
        return;
    }

    public void BroadcastLocalTransition()
    {
        _transition = "BroadcastLocalTransition";
        getState().BroadcastLocalTransition(this);
        _transition = "";
        return;
    }

    public void CancelEventTransition()
    {
        _transition = "CancelEventTransition";
        getState().CancelEventTransition(this);
        _transition = "";
        return;
    }

    public void CreateEventTransition()
    {
        _transition = "CreateEventTransition";
        getState().CreateEventTransition(this);
        _transition = "";
        return;
    }

    public void EventErrorTransition()
    {
        _transition = "EventErrorTransition";
        getState().EventErrorTransition(this);
        _transition = "";
        return;
    }

    public void EventOccurredTransition()
    {
        _transition = "EventOccurredTransition";
        getState().EventOccurredTransition(this);
        _transition = "";
        return;
    }

    public void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(InternalEvent ie)
    {
        _transition = "InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition";
        getState().InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(this, ie);
        _transition = "";
        return;
    }

    public void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(InternalEvent ie)
    {
        _transition = "InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition";
        getState().InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(this, ie);
        _transition = "";
        return;
    }

    public void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(InternalEvent ie)
    {
        _transition = "InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition";
        getState().InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(this, ie);
        _transition = "";
        return;
    }

    public void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(InternalEvent ie)
    {
        _transition = "InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition";
        getState().InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(this, ie);
        _transition = "";
        return;
    }

    public void QueryAuthorityTransition()
    {
        _transition = "QueryAuthorityTransition";
        getState().QueryAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void QueryControlTransition()
    {
        _transition = "QueryControlTransition";
        getState().QueryControlTransition(this);
        _transition = "";
        return;
    }

    public void QueryEventsTransition()
    {
        _transition = "QueryEventsTransition";
        getState().QueryEventsTransition(this);
        _transition = "";
        return;
    }

    public void QueryLocalPoseTransition()
    {
        _transition = "QueryLocalPoseTransition";
        getState().QueryLocalPoseTransition(this);
        _transition = "";
        return;
    }

    public void QueryTimeoutTransition()
    {
        _transition = "QueryTimeoutTransition";
        getState().QueryTimeoutTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition()
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this);
        _transition = "";
        return;
    }

    public void ReceiveTransition(QueryLocalPose msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReceiveTransition(SetLocalPose msg, Receive.Body.ReceiveRec transportData)
    {
        _transition = "ReceiveTransition";
        getState().ReceiveTransition(this, msg, transportData);
        _transition = "";
        return;
    }

    public void ReleaseControlTransition()
    {
        _transition = "ReleaseControlTransition";
        getState().ReleaseControlTransition(this);
        _transition = "";
        return;
    }

    public void RequestControlTransition()
    {
        _transition = "RequestControlTransition";
        getState().RequestControlTransition(this);
        _transition = "";
        return;
    }

    public void SendTransition()
    {
        _transition = "SendTransition";
        getState().SendTransition(this);
        _transition = "";
        return;
    }

    public void SetAuthorityTransition()
    {
        _transition = "SetAuthorityTransition";
        getState().SetAuthorityTransition(this);
        _transition = "";
        return;
    }

    public void SetLocalPoseTransition()
    {
        _transition = "SetLocalPoseTransition";
        getState().SetLocalPoseTransition(this);
        _transition = "";
        return;
    }

    public void TimeoutTransition()
    {
        _transition = "TimeoutTransition";
        getState().TimeoutTransition(this);
        _transition = "";
        return;
    }

    public void UpdateEventTransition()
    {
        _transition = "UpdateEventTransition";
        getState().UpdateEventTransition(this);
        _transition = "";
        return;
    }

    public LocalPoseSensor_ReceiveFSMState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((LocalPoseSensor_ReceiveFSMState) _state);
    }

    protected LocalPoseSensor_ReceiveFSM getOwner()
    {
        return (_owner);
    }

    public void setOwner(LocalPoseSensor_ReceiveFSM owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private LocalPoseSensor_ReceiveFSM _owner;

    public static abstract class LocalPoseSensor_ReceiveFSMState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected LocalPoseSensor_ReceiveFSMState(String name, int id)
        {
            super (name, id);
        }

        protected void Entry(LocalPoseSensor_ReceiveFSMContext context) {}
        protected void Exit(LocalPoseSensor_ReceiveFSMContext context) {}

        protected void BroadcastGlobalTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void BroadcastLocalTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CancelEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void CreateEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventErrorTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void EventOccurredTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            Default(context);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            Default(context);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            Default(context);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            Default(context);
        }

        protected void QueryAuthorityTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryEventsTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryLocalPoseTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void QueryTimeoutTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context, QueryLocalPose msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context, SetLocalPose msg, Receive.Body.ReceiveRec transportData)
        {
            Default(context);
        }

        protected void ReleaseControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void RequestControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void SendTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void SetAuthorityTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void SetLocalPoseTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void TimeoutTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void UpdateEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {
            Default(context);
        }

        protected void Default(LocalPoseSensor_ReceiveFSMContext context)
        {
            if (context.getDebugFlag() == true)
            {
                PrintStream str = 
                    context.getDebugStream();

                str.println(
                    "TRANSITION   : Default");
            }

            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class LocalPoseSensor_ReceiveFSM_SM
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //
        public static final LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled Receiving_Ready_NotControlled =
            new LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled("LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled", 0);
        public static final LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled Receiving_Ready_Controlled =
            new LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled("LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled", 1);
        public static final LocalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE Internally_Generated_State_DO_NOT_USE =
            new LocalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE("LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE", 2);
        private static final LocalPoseSensor_ReceiveFSM_SM_Default Default =
            new LocalPoseSensor_ReceiveFSM_SM_Default("LocalPoseSensor_ReceiveFSM_SM.Default", -1);

    }

    protected static class LocalPoseSensor_ReceiveFSM_SM_Default
        extends LocalPoseSensor_ReceiveFSMState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected LocalPoseSensor_ReceiveFSM_SM_Default(String name, int id)
        {
            super (name, id);
        }
    //-----------------------------------------------------------
    // Member data.
    //
    }

    private static final class LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled
        extends LocalPoseSensor_ReceiveFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_NotControlled(String name, int id)
        {
            super (name, id);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled");
            }

            (context.getState()).Exit(context);
            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(InternalEvent ie)");
            }

            context.clearState();
            try
            {
                ctxt.processNotifications("Receiving_Ready_Controlled", ie);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_ControlledTransition(InternalEvent ie)");
                }

                context.setState(LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled);
                (context.getState()).Entry(context);
            }
            return;
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context, QueryLocalPose msg, Receive.Body.ReceiveRec transportData)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled");
            }
            LocalPoseSensor_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled.ReceiveTransition(QueryLocalPose msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.SendAction("ReportLocalPose", transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled.ReceiveTransition(QueryLocalPose msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled
        extends LocalPoseSensor_ReceiveFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private LocalPoseSensor_ReceiveFSM_SM_Receiving_Ready_Controlled(String name, int id)
        {
            super (name, id);
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled");
            }

            (context.getState()).Exit(context);
            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(InternalEvent ie)");
            }

            context.clearState();
            try
            {
                ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_ReceivingTransition(InternalEvent ie)");
                }

                context.setState(LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled);
                (context.getState()).Entry(context);
            }
            return;
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled");
            }

            (context.getState()).Exit(context);
            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(InternalEvent ie)");
            }

            context.clearState();
            try
            {
                ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_ReadyTransition(InternalEvent ie)");
                }

                context.setState(LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled);
                (context.getState()).Entry(context);
            }
            return;
        }

        protected void InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(LocalPoseSensor_ReceiveFSMContext context, InternalEvent ie)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled");
            }

            (context.getState()).Exit(context);
            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(InternalEvent ie)");
            }

            context.clearState();
            try
            {
                ctxt.processNotifications("Receiving_Ready_NotControlled", ie);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.InternalStateChange_To_LocalPoseSensor_ReceiveFSM_Receiving_Ready_NotControlledTransition(InternalEvent ie)");
                }

                context.setState(LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_NotControlled);
                (context.getState()).Entry(context);
            }
            return;
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context, QueryLocalPose msg, Receive.Body.ReceiveRec transportData)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled");
            }
            LocalPoseSensor_ReceiveFSMState endState = context.getState();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.ReceiveTransition(QueryLocalPose msg, Receive.Body.ReceiveRec transportData)");
            }

            context.clearState();
            try
            {
                ctxt.SendAction("ReportLocalPose", transportData);
            }
            finally
            {
                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.ReceiveTransition(QueryLocalPose msg, Receive.Body.ReceiveRec transportData)");
                }

                context.setState(endState);
            }
            return;
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context, SetLocalPose msg, Receive.Body.ReceiveRec transportData)
        {
            LocalPoseSensor_ReceiveFSM ctxt = context.getOwner();

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled");
            }
            if (ctxt.isControllingClient( transportData ))
            {
                LocalPoseSensor_ReceiveFSMState endState = context.getState();

                if (context.getDebugFlag() == true)
                {
                    PrintStream str = context.getDebugStream();

                    str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.ReceiveTransition(SetLocalPose msg, Receive.Body.ReceiveRec transportData)");
                }

                context.clearState();
                try
                {
                    ctxt.updateLocalPoseAction(msg);
                }
                finally
                {
                    if (context.getDebugFlag() == true)
                    {
                        PrintStream str = context.getDebugStream();

                        str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Receiving_Ready_Controlled.ReceiveTransition(SetLocalPose msg, Receive.Body.ReceiveRec transportData)");
                    }

                    context.setState(endState);
                }
            }
            else
            {
                super.ReceiveTransition(context, msg, transportData);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }

    private static final class LocalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE
        extends LocalPoseSensor_ReceiveFSM_SM_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private LocalPoseSensor_ReceiveFSM_SM_Internally_Generated_State_DO_NOT_USE(String name, int id)
        {
            super (name, id);
        }

        protected void BroadcastGlobalTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastGlobalTransition()");
            }

            return;
        }

        protected void BroadcastLocalTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.BroadcastLocalTransition()");
            }

            return;
        }

        protected void CancelEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CancelEventTransition()");
            }

            return;
        }

        protected void CreateEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.CreateEventTransition()");
            }

            return;
        }

        protected void EventErrorTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventErrorTransition()");
            }

            return;
        }

        protected void EventOccurredTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.EventOccurredTransition()");
            }

            return;
        }

        protected void QueryAuthorityTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryAuthorityTransition()");
            }

            return;
        }

        protected void QueryControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryControlTransition()");
            }

            return;
        }

        protected void QueryEventsTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryEventsTransition()");
            }

            return;
        }

        protected void QueryLocalPoseTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryLocalPoseTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryLocalPoseTransition()");
            }

            return;
        }

        protected void QueryTimeoutTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.QueryTimeoutTransition()");
            }

            return;
        }

        protected void ReceiveTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReceiveTransition()");
            }

            return;
        }

        protected void ReleaseControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.ReleaseControlTransition()");
            }

            return;
        }

        protected void RequestControlTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.RequestControlTransition()");
            }

            return;
        }

        protected void SendTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SendTransition()");
            }

            return;
        }

        protected void SetAuthorityTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SetAuthorityTransition()");
            }

            return;
        }

        protected void SetLocalPoseTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SetLocalPoseTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.SetLocalPoseTransition()");
            }

            return;
        }

        protected void TimeoutTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.TimeoutTransition()");
            }

            return;
        }

        protected void UpdateEventTransition(LocalPoseSensor_ReceiveFSMContext context)
        {

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            if (context.getDebugFlag() == true)
            {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : LocalPoseSensor_ReceiveFSM_SM.LocalPoseSensor_ReceiveFSM_SM.Internally_Generated_State_DO_NOT_USE.UpdateEventTransition()");
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
